<a href="https://colab.research.google.com/github/AnjulaMehto/MCA/blob/main/MCA2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("Hello World")


Hello World


In [ ]:
a = 10
b = 220
c = a + b       # Add two numbers
print (a, " + ", b, " --> ", c)

10  +  220  -->  230


In [1]:
print("hello")

hello


In [ ]:
a = "Bhagat"
b = " Singh"
c = a + b		# Concatinate two strings
print (a, " + ", b, " --> ", c)

Bhagat  +   Singh  -->  Bhagat Singh


In [ ]:
a = "Bhagat"
b = 100
c = a + str(b)		# Concatinate string with number
print (a, " + ", b, " --> ", c)

Bhagat  +  100  -->  Bhagat100


In [ ]:
a = input("Enter First String: ")
b = input("Enter Second String: ")
c = a + b		# concatinate two strings
print  (a, " + ", b, "      --> ", c)

# Run the program with (1) Two strings and (2) Two numbers

Enter First String: abc
Enter Second String: def
abc  +  def       -->  abcdef


In [ ]:
a = int(input("Enter First No: "))
b = int(input("Enter Second No: "))
c = a + b
print (a, " + ", b, " --> ", c)

Enter First No: 10
Enter Second No: 25
10  +  25  -->  35


In [ ]:
i=1
while i <= 10:
	print (i)
	i = i+1

1
2
3
4
5
6
7
8
9
10


In [ ]:
#NumPy (1D and 2D array)
import numpy as np

# Creating a 1D array
arr_1d = np.array([1, 2, 3])

# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Displaying the arrays
print("1D Array:")
print(arr_1d)

print("\n2D Array:")
print(arr_2d)

1D Array:
[1 2 3]

2D Array:
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

# Given matrix
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# i. Sum of all elements
total_sum = np.sum(gfg)

# ii. Sum of all elements row-wise
row_sum = np.sum(gfg, axis=1)

# iii. Sum of all elements column-wise
col_sum = np.sum(gfg, axis=0)

# Displaying the results
print("Matrix:")
print(gfg)

print("\ni. Sum of all elements:", total_sum)

print("\nii. Sum of all elements row-wise:")
print(row_sum)

print("\niii. Sum of all elements column-wise:")
print(col_sum)

Matrix:
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

i. Sum of all elements: 45

ii. Sum of all elements row-wise:
[[14]
 [16]
 [15]]

iii. Sum of all elements column-wise:
[[20  9 16]]


In [ ]:
import numpy as np

# Given arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

# Compare arrays
are_equal = np.array_equal(arr1, arr2)

# Display the result
if are_equal:
    print("Arrays are equal.")
else:
    print("Arrays are not equal.")

Arrays are equal.


In [ ]:
import numpy as np

# i. Array x
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

# Find unique values and their counts
unique_values_x, counts_x = np.unique(x, return_counts=True)

# Find the index of the most frequent value(s)
most_frequent_index_x = np.argmax(counts_x)

# Display the results for array x
most_frequent_value_x = unique_values_x[most_frequent_index_x]
indices_x = np.where(x == most_frequent_value_x)[0]

print("For array x:")
print("Most frequent value:", most_frequent_value_x)
print("Indices of the most frequent value(s):", indices_x)

# ii. Array y
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

# Find unique values and their counts
unique_values_y, counts_y = np.unique(y, return_counts=True)

# Find the index of the most frequent value(s)
most_frequent_index_y = np.argmax(counts_y)

# Display the results for array y
most_frequent_value_y = unique_values_y[most_frequent_index_y]
indices_y = np.where(y == most_frequent_value_y)[0]

print("\nFor array y:")
print("Most frequent value:", most_frequent_value_y)
print("Indices of the most frequent value(s):", indices_y)


For array x:
Most frequent value: 1
Indices of the most frequent value(s): [0 5 7 8 9]

For array y:
Most frequent value: 1
Indices of the most frequent value(s): [0 1 2]
